services:
  mongodb:
    image: mongo:8.0.3
    container_name: service_flow_control-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: service_flow_control
    ports:
      - "27018:27017"
    
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: service_flow_control-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672