spring:
  application:
    name: service-flow-control
    data:
      mongodb:
        uri: mongodb://root:root@localhost:27018/service_flow_control
        database: service_flow_control
        connection-timeout: 1000
        socket-timeout: 3000


server:
  port: 8081
  servlet:
    context-path: /service-flow-control