spring:
  application:
    name: registrations

  datasource:
    url: jdbc:postgresql://localhost:5435/dadapetshop_registrations
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:/db/migration

server:
  servlet:
    context-path: /registrations